//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PowerStamper.rc
//
#define IDS_CLASSNAME                   1
#define IDS_PARAMETERS                  2
#define IDS_LIBDESC                     4
#define IDS_CATEGORY                    5
#define IDS_MULTISEL                    6
#define IDS_NONESEL                     7
#define IDS_SET_INPUT_BMP               8
#define IDS_OUT_MULTIPLE_BMPS           9
#define IDS_OUT_NONE_BMP                10
#define IDS_SET_OUTPUT_BMP              11
#define IDS_ASK_DELETEFILE              12
#define IDS_ASK_DELETEGROUP             13
#define IDS_USER_NAME                   14
#define IDS_COMPANY                     15
#define IDS_CANCEL_PAINT                16
#define IDS_SERIAL_NUMBER               17
#define IDS_SIMPLE                      18
#define IDS_FRAMEMOD_CLASSNAME          19
#define IDS_REQ_AUTH                    20
#define IDD_OUTSIZE                     101
#define IDD_SKELUTIL                    102
#define IDD_NEBBIUTIL                   102
#define IDD_INSIZE                      103
#define IDD_OUTBMP_BYMATID              104
#define IDD_NUM_GROUPS                  105
#define IDR_OUTBMPS_MENU                106
#define IDB_ABOUT                       114
#define IDB_ABOUT_MASK                  115
#define IDD_LOG_DLG                     118
#define IDB_PS_LOGO                     119
#define IDB_MANKUA_WHITE                121
#define IDB_MANKUA_BLACK                122
#define IDB_HELP_MASK                   123
#define IDB_HELP                        124
#define IDB_BANNER_CRACKART             125
#define IDD_ABOUT                       163
#define IDC_BTN1                        1000
#define IDC_PAINT_OUT                   1000
#define IDC_CLOSE                       1001
#define IDC_SEL_NAME                    1002
#define IDC_RENDER_IN                   1007
#define IDC_OBS_WIDTH_SPIN              1008
#define IDC_OBS_WIDTH                   1009
#define IDC_OBS_HEIGHT_SPIN             1010
#define IDC_PERCENT                     1010
#define IDC_OBS_HEIGHT                  1011
#define IDC_SIZE_VIEWPORT               1011
#define IDC_SIZE_CUSTOM                 1012
#define IDC_IBS_HEIGHT                  1013
#define IDC_IBS_WIDTH                   1014
#define IDC_IBS_WIDTH_SPIN              1015
#define IDC_IBS_HEIGHT_SPIN             1016
#define IDC_SIZE_IN                     1017
#define IDC_IBS_ASPECT_SPIN             1017
#define IDC_SET_INBMP                   1018
#define IDC_IBS_ASPECT                  1018
#define IDC_SET_OUTBMP                  1019
#define IDC_SET_OUTBMP_0                1019
#define IDC_SET_OUTBMP_1                1020
#define IDC_SET_OUTBMP_2                1021
#define IDC_SET_OUTBMP_3                1022
#define IDC_SET_OUTBMP_4                1023
#define IDC_SET_SIZE_0                  1024
#define IDC_SET_SIZE_1                  1025
#define IDC_SET_SIZE_2                  1026
#define IDC_SET_SIZE_3                  1027
#define IDC_SET_SIZE_4                  1028
#define IDC_OUTDLG_SCROLL               1029
#define IDC_SET_NUMGROUPS               1031
#define IDC_TXT_NUMGROUPS               1032
#define IDC_NUMGROUPS_EDIT              1033
#define IDC_GROUP_DELETE_0              1033
#define IDC_NUMGROUPS_SPIN              1034
#define IDC_GROUP_DELETE_1              1034
#define IDC_NEB_SAMP_EDIT               1035
#define IDC_GROUP_DELETE_2              1035
#define IDC_NEB_SAMP_SPIN               1036
#define IDC_GROUP_DELETE_3              1036
#define IDC_NEB_PREF_EDIT               1037
#define IDC_GROUP_DELETE_4              1037
#define IDC_NEB_PREF_SPIN               1038
#define IDC_GROUP_USE_0                 1038
#define IDC_GROUP_USE_1                 1039
#define IDC_NEB_ANGS_EDIT               1039
#define IDC_GROUP_USE_2                 1040
#define IDC_NEB_ANGS_SPIN               1040
#define IDC_GROUP_USE_3                 1041
#define IDC_NEB_ANGE_EDIT               1041
#define IDC_GROUP_USE_4                 1042
#define IDC_NEB_ANGE_SPIN               1042
#define IDC_PRE_ALPHA                   1044
#define IDC_USER                        1045
#define IDC_COMPANY                     1046
#define IDC_SERIAL                      1047
#define IDC_LOG                         1051
#define IDC_LOG_TEXT                    1052
#define IDC_MANKUA                      1057
#define IDC_BANNER                      1058
#define IDC_NEBBI_ABOUT                 1152
#define IDC_NEBBI_ABOUT2                1153
#define IDC_NEBBI_HELP                  1153
#define IDC_MATID_EDIT_0                1157
#define IDC_MATID_EDIT_1                1158
#define IDC_MATID_EDIT_2                1159
#define IDC_MATID_EDIT_3                1160
#define IDC_MATID_EDIT_4                1161
#define IDC_MATID_SPIN_0                1163
#define IDC_MATID_SPIN_1                1164
#define IDC_MATID_SPIN_2                1165
#define IDC_MATID_SPIN_3                1166
#define IDC_MATID_SPIN_4                1167
#define IDC_UVW_SPIN_0                  1172
#define IDC_UVW_SPIN_1                  1173
#define IDC_UVW_SPIN_2                  1174
#define IDC_UVW_SPIN_3                  1175
#define IDC_UVW_SPIN_4                  1176
#define IDC_UVW_EDIT_0                  1177
#define IDC_UVW_EDIT_1                  1178
#define IDC_UVW_EDIT_2                  1179
#define IDC_UVW_EDIT_3                  1180
#define IDC_UVW_EDIT_4                  1181
#define IDM_DEL_OUTFILE                 40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
